#!/bin/sh

mkdir -p /proc
mount -t proc proc /proc

mkdir -p /sys
mount -t sysfs sysfs /sys

mkdir -p /sys/kernel/debug
mount -t debugfs debugfs /sys/kernel/debug

mkdir -p /dev
mount -t devtmpfs devtmpfs /dev

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

mkdir -p /shared
mount -t 9p -o trans=virtio shared /shared

ln -s /shared/lib /
